#pragma once


#include "FileIO/TestCancelIo.h"
#include "FileIO/TestCancelIoEx.h"
#include "FileIO/TestCancelSynchronousIo.h"
#include "FileIO/TestCreateIoCompletionPort.h"
#include "FileIO/TestFlushFileBuffers.h"
#include "FileIO/TestGetQueuedCompletionStatus.h"
#include "FileIO/TestGetQueuedCompletionStatusEx.h"
#include "FileIO/TestLockFile.h"
#include "FileIO/TestLockFileEx.h"
#include "FileIO/TestPostQueuedCompletionStatus.h"
#include "FileIO/TestReadFile.h"
#include "FileIO/TestReadFileEx.h"
#include "FileIO/TestReadFileScatter.h"
#include "FileIO/TestSetEndOfFile.h"
#include "FileIO/TestSetFileCompletionNotificationModes.h"
#include "FileIO/TestSetFileIoOverlappedRange.h"
#include "FileIO/TestSetFilePointer.h"
#include "FileIO/TestSetFilePointerEx.h"
#include "FileIO/TestUnlockFile.h"
#include "FileIO/TestUnlockFileEx.h"
#include "FileIO/TestWriteFile.h"
#include "FileIO/TestWriteFileEx.h"
#include "FileIO/TestWriteFileGather.h"
#include "FileIO/TestCreateFileMapping.h"