#pragma once;

bool MakeFile(TestLog& log, const std::wstring& lpFileName);
bool MakeFile(TestLog& log, const std::wstring& lpFileName, size_t iFileSizeKB);
bool MakeFile(TestLog& log, const std::wstring& lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode);
bool MakeFile(TestLog& log, const std::wstring& lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, size_t buffersizeKB);
bool MakeFile(TestLog& log, const std::wstring& lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, size_t iFileSizeKB, size_t buffersizeKB);
bool DeleteFileOrCheck(TestLog& log, const std::wstring& lpFileName);
bool CheckFileData(TestLog& log, const std::wstring& lpFileName);
bool CheckFileData(TestLog& log, const std::wstring& lpFileName, INT32 iFileSizeKB);
bool CheckFileData(TestLog& log, const std::wstring& lpFileName, INT32 iFileSizeKB, size_t buffersizeKB);
bool TouchFile(TestLog& log, LPCWSTR lpFileName);
bool TouchFile(TestLog& log, const std::wstring& filename);
std::wstring GetUniqueFileName(const std::wstring& parentDirPath);
bool EndOfThePathIsBackSlash(const std::wstring& path);
std::wstring GetWidTestBasePath();
bool FillDummyData(const std::wstring& path);
bool AreBothOfFilesDataEqual(const std::wstring& path1, const std::wstring& path2);
BOOL IsFileExist(const std::wstring& strFullPath);
std::wstring GetCurrentModulePath();
std::wstring FileTimeToString(FILETIME ft);
std::wstring FileSizeToString(DWORD nFileSizeHigh, DWORD nFileSizeLow);
std::wstring IntegerToString(INT32 i);
BOOL CreateDirectoryWithAttributes(TestLog& log, const std::wstring& path, DWORD dwAttribute);
BOOL IsVistaOrLater();
std::wstring GetLastErrorStr();
BOOL TouchManyFiles(TestLog& log, size_t iFileNum, const std::wstring& basePath, std::vector<std::wstring>& vCreatedFiles, bool fDirectory);
void CreateSubDir(LPCTSTR lpszFileFullPath);
BOOL MakeManyFiles(TestLog& log, size_t iFileNum, INT32 iFileSize, const std::wstring& basePath, std::vector<std::wstring>& vCreatedFiles);
void OpenMSWord(size_t n);
std::wstring GetSrcFileName();
std::wstring GetDstFileName();
std::wstring GetTestFileName();
std::wstring GetTestFileName(const std::wstring& filename);
bool IsTimeToEnd();
bool IsTimeToStart();
void WaitUntilStartTime();